### ISSUE TITLE
One Way Collision shapes cause instability when multiple objects are stacked.

### ISSUE THREAD

**Issue by DragonEngineer** [appsinacup/godot-rapier-physics#162] opened 2024-07-24 13:39 UTC
**Describe the bug**

If you have 2 or rigidbodies (godot icons thing) stacking on top of another, the bottom most rigidbody will clip into the staticbody (magenta thing)
![image](https://github.com/user-attachments/assets/2d7b26f1-29ec-42ad-b9be-62ef88e00d06)

**To Reproduce**

1. Put many "Box" object on top of the "Belt" object
2. Run the game

**Expected behavior**
The bottom most rigidbody should rest right on top of the magenta block, not partially sunk into the magenta block

**Environment:**
 - OS: Windows 10
 - Version 0.7.18
 - Godot Version 4.2.1
 - Type SIMD Single 2D
 - CPU: AMD Ryzen 7 4800H with Radeon Graphics
 - GPU: Nvidia Geforce GTX 1650

**Files**
[Factory Boxes.zip](https://github.com/user-attachments/files/16362826/Factory.Boxes.zip)
- After downloading, need to put the Rapier (SIMD Single 2D) addons inside the addons folder before opening the project
- You can run "test_level.tscn" to see the bug

**Comment by Ughuuu** [comment] 2024-07-24 13:46
Seems that if you disable one_way_collision on the shape, everything works. Possibly the problem is in the modify_contacts of the one_way_collision logic.

**Comment by Ughuuu** [comment] 2024-08-24 13:14
One way collision will get fixed soon by open PR, next thing to look into at this issue is move_and_slide call getting call, that might cause some instability too.

**Comment by Ughuuu** [comment] 2024-08-27 15:50
Fixed in 0.8.1. It was indeed caused by one way direction that has been reworked to be more stable.

https://github.com/user-attachments/assets/b45617c5-776c-4c1c-8927-230378b6e295

I do acknowledge that it does pass a bit into the object. Probably that can be another issue.

**Closed by Ughuuu** 2024-08-27 15:50 UTC
Labels: bug
